### ISSUE TITLE
The tool tries to run Randoop even if compilation fails

### ISSUE THREAD

**Issue by clenimar** [alyssonfm/jmlok#1]
By running our tool with a project that has compilation errors, CSC shows error messages and compilation fails, but randoop is called anyway.

**Comment by ddspog** [comment]
The problem has easy solution, but as the focus is to end all steps at
Detection phase. We should treat this later, as we need to test the
generation test phase a lot more.

Em Sun Dec 21 2014 at 17:18:21, C. Filemon notifications@github.com
escreveu:

**Comment by clenimar** [comment]
okay. There are more two bugs we and Alysson have found... I'm gonna post them later.

[]s
